# Generated by Django 3.0.6 on 2020-05-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='stuff',
            new_name='quantity',
        ),
    ]
