# Generated by Django 3.0.6 on 2020-05-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200515_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='quantity',
            new_name='quantities',
        ),
    ]
