# Generated by Django 3.0.6 on 2020-05-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seasonned_tips',
        ),
    ]
