# Generated by Django 3.0.6 on 2020-05-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_seasonned_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='beginner_tips',
        ),
    ]
