# Generated by Django 3.0.6 on 2020-05-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_beginner_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='beginner_tips',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
