# Generated by Django 3.0.6 on 2020-06-24 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campspots', '0001_initial'),
        ('checkout', '0009_auto_20200619_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='campspot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campspots.Campspot'),
        ),
    ]
