# Generated by Django 3.0.6 on 2020-07-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_remove_order_grand_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
    ]
