# Generated by Django 3.0.6 on 2020-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200508_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lateArrival',
            field=models.BooleanField(default=True),
        ),
    ]
