# Generated by Django 3.0.6 on 2020-05-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='pitch_sizes',
        ),
    ]
