# Generated by Django 3.0.6 on 2020-05-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campspots',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('pitch_sizes', models.BooleanField(blank=True, default=False, null=True)),
                ('lateArrival', models.BooleanField(default=True)),
            ],
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('starter', models.BooleanField(default=True)),
            ],
            bases=('products.product',),
        ),
        migrations.RemoveField(
            model_name='product',
            name='lateArrival',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pitch_sizes',
        ),
    ]
