# Generated by Django 3.0.6 on 2020-05-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200530_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campspots',
            old_name='lateArrival',
            new_name='Ater_eight_Arrival',
        ),
    ]
