# Generated by Django 3.0.6 on 2020-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200530_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campspots',
            name='Ater_eight_Arrival',
        ),
        migrations.AddField(
            model_name='product',
            name='late_arrival',
            field=models.BooleanField(default=True),
        ),
    ]
