# Generated by Django 3.0.6 on 2020-05-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200531_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='late_arrival',
            new_name='lateArrival',
        ),
    ]
