# Generated by Django 3.0.6 on 2020-05-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200531_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lateArrival',
        ),
    ]
