# Generated by Django 3.0.6 on 2020-05-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200520_1043'),
        ('products', '0011_remove_product_latearrival'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campspots',
        ),
    ]
