# Generated by Django 3.0.6 on 2020-05-31 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_campspots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campspots',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('pitch_sizes', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='lateArrival',
            field=models.BooleanField(default=True),
        ),
    ]
