# Generated by Django 3.0.6 on 2020-05-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200520_1043'),
        ('products', '0013_auto_20200531_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('available', models.BooleanField(default=True)),
            ],
            bases=('products.product',),
        ),
        migrations.RenameModel(
            old_name='Physical',
            new_name='Goods',
        ),
    ]
