# Generated by Django 3.0.6 on 2020-05-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200520_1043'),
        ('products', '0014_auto_20200531_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='product_ptr',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lateArrival',
            new_name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='pitch_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='starter',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Campspots',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
