# Generated by Django 3.0.6 on 2020-05-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200531_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='lateArrival',
        ),
    ]
