# Generated by Django 3.0.6 on 2020-05-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200531_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='lateArrival',
        ),
    ]
